# Practicum 1 — dynamic bank closure

This notebook estimates monetary closure cost, cross-fitted closure CCPs,
conditional continuation values, and the structural parameters requested by
the submission template.

A/B use calibrated beta=0.96. C uses beta=0.70. Beta is displayed for
transparency but is not a submission row.

In [2]:
from pathlib import Path

import pandas as pd

from dse_practicum import (
    P1CounterfactualConfig,
    P1FitConfig,
    fit_practicum1,
    fit_practicum1_all,
)

ROOT = next(
    candidate
    for candidate in (Path.cwd(), *Path.cwd().parents)
    if (candidate / "practicum" / "practicum1" / "data").exists()
)

DATA = ROOT / "practicum" / "practicum1" / "data"
DATA

PosixPath('/Users/bc3139/repo/summer2026/DSE2026/practicum/practicum1/data')

## 1. Fit one dataset first

This is the recommended debugging workflow. The full settings use three CCP
folds and 200 boosting iterations.

In [3]:
config = P1FitConfig()

result_a = fit_practicum1(
    DATA / "set_A.parquet",
    spec="A",
    config=config,
)
result_a.summary()

                                      estimate
quantity
sigma                                47.813325
beta (calibration; not submitted)     0.960000
theta_const                        -356.161916
theta_log_assets                    459.366358
theta_log_assets^2                  -20.268342
theta_npf_a                        6821.286014
theta_roa                          -829.263120
theta_realest_a                    4516.696201
theta_house                           0.038824
theta_house*npf_a                  -168.711315

In [4]:
pd.Series(result_a.diagnostics, name="value").to_frame()

                                               value
n_rows                                 154068.000000
n_banks                                  8000.000000
n_failures                               4510.000000
monetary_cost_rmse                        200.176235
monetary_cost_r_squared                     0.681820
ccp_event_rate                              0.029273
ccp_log_loss                                0.128571
ccp_brier_score                             0.028230
ccp_roc_auc                                 0.650610
ccp_probability_min                         0.001067
ccp_probability_max                         0.429248
continuation_r2_log_close_probability       0.730925
continuation_r2_monetary_cost               0.873030
continuation_r2_x:const                     1.000000
continuation_r2_x:log_assets                0.969786
continuation_r2_x:log_assets^2              0.969745
continuation_r2_x:npf_a                     0.860664
continuation_r2_x:roa                       0.885506
continuation_r2_x:realest_a                 0.851331
continuation_r2_x:house                     0.750214
continuation_r2_x:house*npf_a               0.778204
gmm_j_statistic                         35092.982417
gmm_n_moments                              43.000000
gmm_n_observations                     146068.000000

Useful diagnostics:

- monetary-cost R-squared should be reasonably high;
- CCP probabilities must not be concentrated at the clipping bounds;
- continuation R-squared values show whether the one-period transition
  approximation is working;
- the structural fit must converge.

In [5]:
{
    "structural_converged": result_a.structural.converged,
    "sigma": result_a.structural.sigma,
    "calibrated_beta": result_a.structural.beta,
    "ccp_auc": result_a.ccp.diagnostics["roc_auc"],
    "gmm_j": result_a.structural.j_statistic,
}

{'structural_converged': True,
 'sigma': 47.81332478381348,
 'calibrated_beta': 0.96,
 'ccp_auc': 0.6506097012426476,
 'gmm_j': 35092.982417172105}

## 2. Sensitivity to beta

This does not change the official default. It is useful for checking the
calibration. `estimate_beta=True` estimates beta as a nuisance parameter,
but it is weakly identified and may approach its upper bound.

In [6]:
# sensitivity_a = fit_practicum1(
#     DATA / "set_A.parquet",
#     spec="A",
#     config=P1FitConfig(fixed_beta=0.95),
# )
# sensitivity_a.summary()

In [7]:
# weak_id_check = fit_practicum1(
#     DATA / "set_A.parquet",
#     spec="A",
#     config=P1FitConfig(estimate_beta=True),
# )
# weak_id_check.summary()

## 3. Fit A, B, and C

In [8]:
all_results = fit_practicum1_all(DATA, config=config)
all_results.summary()

   dataset                           quantity     estimate
0        A                              sigma    47.813325
1        A  beta (calibration; not submitted)     0.960000
2        A                        theta_const  -356.161916
3        A                   theta_log_assets   459.366358
4        A                 theta_log_assets^2   -20.268342
5        A                        theta_npf_a  6821.286014
6        A                          theta_roa  -829.263120
7        A                    theta_realest_a  4516.696201
8        A                        theta_house     0.038824
9        A                  theta_house*npf_a  -168.711315
10       B                              sigma    50.536245
11       B  beta (calibration; not submitted)     0.960000
12       B                        theta_const -1507.313831
13       B                   theta_log_assets   606.826567
14       B                 theta_log_assets^2   -24.907838
15       B                        theta_npf_a  7251.114347
16       B                          theta_roa  -785.546680
17       B                    theta_realest_a  4317.627457
18       B                        theta_house  -208.702877
19       B             theta_house*log_assets    16.914116
20       C                              sigma   183.284639
21       C  beta (calibration; not submitted)     0.700000
22       C                        theta_const  1104.045220
23       C                   theta_log_assets   180.334951
24       C                 theta_log_assets^2   -11.995034
25       C                        theta_npf_a  8089.867854
26       C                          theta_roa -2120.556524
27       C                    theta_realest_a  6022.115236
28       C                       theta_senate   -11.109898
29       C                        theta_trend    91.102371

## 4. Provisional counterfactuals

The local instruction does not define the shock magnitude, horizon, or
reported statistic. The following cell must therefore be consciously enabled.
Its assumptions are:

- `no_political`: set `house` and `senate` to zero;
- `myopic`: set beta to zero;
- `npl_stress`: add one sample standard deviation to `npf_a`;
- report the one-period mean closure-probability level.

Replace this block when the organizer supplies the exact definitions.

In [9]:
provisional_cf = P1CounterfactualConfig(
    acknowledge_provisional=True,
    npl_shift_in_standard_deviations=1.0,
    report="level",
)

all_results_with_cf = fit_practicum1_all(
    DATA,
    config=config,
    counterfactual_config=provisional_cf,
)
all_results_with_cf.summary()

/Users/bc3139/repo/summer2026/DSE2026/src/dse_practicum/practicum1.py:1002: RuntimeWarning: Practicum 1 counterfactual definitions are provisional: reporting one-period mean closure probabilities.
  result.counterfactuals = compute_provisional_counterfactuals(
/Users/bc3139/repo/summer2026/DSE2026/src/dse_practicum/practicum1.py:1002: RuntimeWarning: Practicum 1 counterfactual definitions are provisional: reporting one-period mean closure probabilities.
  result.counterfactuals = compute_provisional_counterfactuals(
/Users/bc3139/repo/summer2026/DSE2026/src/dse_practicum/practicum1.py:1002: RuntimeWarning: Practicum 1 counterfactual definitions are provisional: reporting one-period mean closure probabilities.
  result.counterfactuals = compute_provisional_counterfactuals(

   dataset                           quantity     estimate
0        A                              sigma    47.813325
1        A  beta (calibration; not submitted)     0.960000
2        A                        theta_const  -356.161916
3        A                   theta_log_assets   459.366358
4        A                 theta_log_assets^2   -20.268342
5        A                        theta_npf_a  6821.286014
6        A                          theta_roa  -829.263120
7        A                    theta_realest_a  4516.696201
8        A                        theta_house     0.038824
9        A                  theta_house*npf_a  -168.711315
10       A                    cf_no_political     0.069018
11       A                          cf_myopic     0.307755
12       A                      cf_npl_stress     0.069341
13       B                              sigma    50.536245
14       B  beta (calibration; not submitted)     0.960000
15       B                        theta_const -1507.313831
16       B                   theta_log_assets   606.826567
17       B                 theta_log_assets^2   -24.907838
18       B                        theta_npf_a  7251.114347
19       B                          theta_roa  -785.546680
20       B                    theta_realest_a  4317.627457
21       B                        theta_house  -208.702877
22       B             theta_house*log_assets    16.914116
23       B                    cf_no_political     0.055893
24       B                          cf_myopic     0.256541
25       B                      cf_npl_stress     0.056838
26       C                              sigma   183.284639
27       C  beta (calibration; not submitted)     0.700000
28       C                        theta_const  1104.045220
29       C                   theta_log_assets   180.334951
30       C                 theta_log_assets^2   -11.995034
31       C                        theta_npf_a  8089.867854
32       C                          theta_roa -2120.556524
33       C                    theta_realest_a  6022.115236
34       C                       theta_senate   -11.109898
35       C                        theta_trend    91.102371
36       C                    cf_no_political     0.029386
37       C                          cf_myopic     0.047253
38       C                      cf_npl_stress     0.031142

## 5. Create the submission file

This uses the official template as the schema and refuses missing, extra, or
non-finite rows.

In [10]:
submission = all_results_with_cf.to_submission(
    DATA / "sample_submission.csv",
    ROOT / "practicum" / "practicum1_submission.csv",
)
submission

                          Id   Prediction
0                    A_sigma    47.813325
1              A_theta_const  -356.161916
2         A_theta_log_assets   459.366358
3       A_theta_log_assets^2   -20.268342
4              A_theta_npf_a  6821.286014
5                A_theta_roa  -829.263120
6          A_theta_realest_a  4516.696201
7              A_theta_house     0.038824
8        A_theta_house*npf_a  -168.711315
9          A_cf_no_political     0.069018
10               A_cf_myopic     0.307755
11           A_cf_npl_stress     0.069341
12                   B_sigma    50.536245
13             B_theta_const -1507.313831
14        B_theta_log_assets   606.826567
15      B_theta_log_assets^2   -24.907838
16             B_theta_npf_a  7251.114347
17               B_theta_roa  -785.546680
18         B_theta_realest_a  4317.627457
19             B_theta_house  -208.702877
20  B_theta_house*log_assets    16.914116
21         B_cf_no_political     0.055893
22               B_cf_myopic     0.256541
23           B_cf_npl_stress     0.056838
24                   C_sigma   183.284639
25             C_theta_const  1104.045220
26        C_theta_log_assets   180.334951
27      C_theta_log_assets^2   -11.995034
28             C_theta_npf_a  8089.867854
29               C_theta_roa -2120.556524
30         C_theta_realest_a  6022.115236
31            C_theta_senate   -11.109898
32             C_theta_trend    91.102371
33         C_cf_no_political     0.029386
34               C_cf_myopic     0.047253
35           C_cf_npl_stress     0.031142