# Practicum 1 - dynamic bank closure

This notebook estimates monetary closure cost, cross-fitted closure CCPs,
conditional continuation values, and the structural parameters requested by
the submission template.

The economic foundation is **Kang, Lowery, and Wardlaw (2015), "The Costs of
Closing Failed Banks."** The most important connection is their Section 1.2,
especially Equations (4)-(9), pp. 1067-1069. A terminal closure action and
Type-I extreme-value choice shocks imply

\[
\sigma\log\frac{p_0(x_t)}{p_1(x_t)}
=
c(x_t)+\beta E\left[
-\sigma\log p_1(x_{t+1})-c(x_{t+1})
\mid x_t,\text{continue}
\right].
\]

This equation avoids solving the complete dynamic program. Estimated choice
probabilities stand in for differences in continuation values, which is the
central Hotz-Miller/CCP insight used by the paper.

Important implementation conventions:

- the practicum reports \(c(x)=MC(x)-\tilde{x}'\theta\), whereas Equation (7)
  in the paper writes the nonmonetary component with the opposite sign;
- A and B use calibrated \(\beta=0.96\), close to the paper's early-period
  estimate in Section 3.4; C uses \(\beta=0.70\), selected from the simulated
  data's GMM profile;
- beta is displayed for transparency but is not a submission row.

Local paper:
[Kang et al. (2015)](../practicum1/ref/Kang-CostsClosingFailed-2015.pdf).

In [1]:
from pathlib import Path

import pandas as pd

from dse_practicum import (
    P1CounterfactualConfig,
    P1FitConfig,
    fit_practicum1,
    fit_practicum1_all,
)

# Locate the repository from either the repository root or the notebook folder.
# This makes the same notebook work in JupyterLab, VS Code, and an executed
# notebook without hard-coding an absolute path.
ROOT = next(
    candidate
    for candidate in (Path.cwd(), *Path.cwd().parents)
    if (candidate / "practicum" / "practicum1" / "data").exists()
)

DATA = ROOT / "practicum" / "practicum1" / "data"
DATA

PosixPath('/Users/bc3139/repo/summer2026/DSE2026/practicum/practicum1/data')

## 1. How the code maps to the paper

`fit_practicum1` follows the five-stage estimator listed in Kang et al.
Section 1.2, p. 1068, with two deliberate adaptations to the simulated data:

1. **Pre-estimate monetary closure cost.** Section 2.2, pp. 1075-1078,
   estimates monetary cost before the structural parameters. The paper uses a
   censored regression because it augments failures with zero-cost unassisted
   mergers. The practicum files contain observed cost only for failed banks
   and contain no merger observations, so the code uses OLS on observed
   `estimated_cost` rows. This preserves the paper's pre-estimation logic
   without inventing the missing censoring observations.
2. **Estimate closure CCPs.** Section 2.4, pp. 1081-1083, uses a flexible
   logit with cubic B-splines. The code uses a flexible histogram gradient
   boosting classifier for the same reduced-form object \(p_1(x)\). It
   cross-fits by `rssd_id`, so no observations from a held-out bank are used
   to predict that bank's probabilities.
3. **Estimate state transitions and continuation objects.** Section 2.3,
   pp. 1079-1081, estimates autoregressive transitions and simulates future
   states. Because Equation (8) is linear in
   \(E[\log p_1(x')]\), \(E[MC(x')]\), and \(E[\tilde{x}']\), the code
   projects these objects directly on a second-degree polynomial of the
   current state using ridge regression. This is a conditional-mean
   approximation to the paper's transition-plus-simulation step.
4. **Estimate structural parameters by GMM.** Equation (8) supplies the
   residual and Equation (9) supplies the moments. Appendix A.1.1, p. 1097,
   recommends instruments that enter payoffs, monetary costs, or transitions.
   The code builds those instruments from the current state and applies
   two-step GMM. The paper uses continuously updated GMM, so the weighting
   update is an approximation, not an exact replication.

These distinctions matter: "paper-inspired" does not mean that the simulated
practicum contains every variable required for a literal replication.

## 2. Fit one dataset first

Fitting A first is the recommended debugging workflow. Explicit numerical
settings below make the computation visible instead of hiding it behind
defaults.

In [2]:
config = P1FitConfig(
    # Three folds balance computation against genuine out-of-bank CCP checks.
    n_ccp_folds=3,
    # A flexible first-stage CCP is important because log(p0/p1) enters the
    # structural equation nonlinearly.
    ccp_max_iter=200,
    # Degree two allows nonlinear conditional means while keeping the
    # continuation projection much smaller than a full transition simulator.
    transition_polynomial_degree=2,
)

# This one function executes the monetary-cost, CCP, continuation, and GMM
# stages described above. Start with one dataset so diagnostics can be checked
# before paying the cost of estimating A, B, and C.
result_a = fit_practicum1(
    DATA / "set_A.parquet",
    spec="A",
    config=config,
)
result_a.summary()

                                      estimate
quantity
sigma                                47.813325
beta (calibration; not submitted)     0.960000
theta_const                        -356.161916
theta_log_assets                    459.366358
theta_log_assets^2                  -20.268342
theta_npf_a                        6821.286014
theta_roa                          -829.263120
theta_realest_a                    4516.696201
theta_house                           0.038824
theta_house*npf_a                  -168.711315

In [3]:
pd.Series(result_a.diagnostics, name="value").to_frame()

                                               value
n_rows                                 154068.000000
n_banks                                  8000.000000
n_failures                               4510.000000
monetary_cost_rmse                        200.176235
monetary_cost_r_squared                     0.681820
ccp_event_rate                              0.029273
ccp_log_loss                                0.128571
ccp_brier_score                             0.028230
ccp_roc_auc                                 0.650610
ccp_probability_min                         0.001067
ccp_probability_max                         0.429248
continuation_r2_log_close_probability       0.730925
continuation_r2_monetary_cost               0.873030
continuation_r2_x:const                     1.000000
continuation_r2_x:log_assets                0.969786
continuation_r2_x:log_assets^2              0.969745
continuation_r2_x:npf_a                     0.860664
continuation_r2_x:roa                       0.885506
continuation_r2_x:realest_a                 0.851331
continuation_r2_x:house                     0.750214
continuation_r2_x:house*npf_a               0.778204
gmm_j_statistic                         35092.982417
gmm_n_moments                              43.000000
gmm_n_observations                     146068.000000

### Why inspect these diagnostics?

The structural step treats monetary cost, CCPs, and continuation expectations
as generated regressors. A numerical optimizer can converge even when those
inputs are poor, so optimizer convergence alone is not enough.

- Monetary-cost \(R^2\) checks the first pre-estimation stage in Section 2.2.
- CCP AUC/log loss and the min/max probability check the flexible choice
  model in Section 2.4. Extremely small probabilities are especially
  dangerous because the structural equation contains their logarithms.
- Continuation \(R^2\) checks the conditional expectations replacing the
  simulations in Section 2.3.
- The GMM convergence flag and \(J\)-statistic assess the final moment system
  discussed in Equation (9) and Appendix A.1.1.

In [4]:
{
    "structural_converged": result_a.structural.converged,
    # sigma is the scale of the Type-I extreme-value choice shock.
    "sigma": result_a.structural.sigma,
    # beta is calibrated for this practicum dataset and is not submitted.
    "calibrated_beta": result_a.structural.beta,
    "ccp_auc": result_a.ccp.diagnostics["roc_auc"],
    "gmm_j": result_a.structural.j_statistic,
}

{'structural_converged': True,
 'sigma': 47.81332478381348,
 'calibrated_beta': 0.96,
 'ccp_auc': 0.6506097012426476,
 'gmm_j': 35092.982417172105}

## 3. Sensitivity to beta

Kang et al. Section 1.2.2 explains that beta is identified only when some
variables shift transitions without directly shifting payoffs. Section 3.4
reports an early-period quarterly estimate around 0.96. Because this
practicum asks for sigma and theta but not beta, the main specification
calibrates beta and treats this cell as a sensitivity exercise.

`estimate_beta=True` is available, but the simulated panel provides weak
standalone identification and the estimate may approach its upper bound.
That boundary behavior is diagnostic evidence, not a value to submit.

In [5]:
# sensitivity_a = fit_practicum1(
#     DATA / "set_A.parquet",
#     spec="A",
#     config=P1FitConfig(fixed_beta=0.95),
# )
# sensitivity_a.summary()

In [6]:
# weak_id_check = fit_practicum1(
#     DATA / "set_A.parquet",
#     spec="A",
#     config=P1FitConfig(estimate_beta=True),
# )
# weak_id_check.summary()

## 4. Fit A, B, and C

The sample-submission file supplies a different \(\tilde{x}\) specification
for each dataset. Passing `spec="A"`, `"B"`, or `"C"` makes the code construct
exactly those nonmonetary-cost terms, including the squared and interaction
terms. This corresponds to changing the covariates in Equation (7), not
searching over specifications.

In [7]:
# Reuse the same first-stage and GMM settings across datasets. Dataset-specific
# theta terms and beta calibrations are selected internally from the label.
all_results = fit_practicum1_all(DATA, config=config)
all_results.summary()

   dataset                           quantity     estimate
0        A                              sigma    47.813325
1        A  beta (calibration; not submitted)     0.960000
2        A                        theta_const  -356.161916
3        A                   theta_log_assets   459.366358
4        A                 theta_log_assets^2   -20.268342
5        A                        theta_npf_a  6821.286014
6        A                          theta_roa  -829.263120
7        A                    theta_realest_a  4516.696201
8        A                        theta_house     0.038824
9        A                  theta_house*npf_a  -168.711315
10       B                              sigma    50.536245
11       B  beta (calibration; not submitted)     0.960000
12       B                        theta_const -1507.313831
13       B                   theta_log_assets   606.826567
14       B                 theta_log_assets^2   -24.907838
15       B                        theta_npf_a  7251.114347
16       B                          theta_roa  -785.546680
17       B                    theta_realest_a  4317.627457
18       B                        theta_house  -208.702877
19       B             theta_house*log_assets    16.914116
20       C                              sigma   183.284639
21       C  beta (calibration; not submitted)     0.700000
22       C                        theta_const  1104.045220
23       C                   theta_log_assets   180.334951
24       C                 theta_log_assets^2   -11.995034
25       C                        theta_npf_a  8089.867854
26       C                          theta_roa -2120.556524
27       C                    theta_realest_a  6022.115236
28       C                       theta_senate   -11.109898
29       C                        theta_trend    91.102371

## 5. Provisional counterfactuals

Kang et al. Section 4, pp. 1093-1096, evaluates **temporary** policy changes.
Appendix A.2, pp. 1098-1100, shows how a one-period counterfactual can retain
the estimated future CCP as the post-policy continuation value and then map a
changed current cost or discount factor into a counterfactual closure
probability. The provisional code below uses that one-period CCP logic.

It is not a literal replication of the paper's policy experiments. The local
practicum instruction names three scenarios but does not define their shock
magnitude, horizon, or reported statistic. The cell must therefore be
consciously enabled and currently assumes:

- `no_political`: set `house` and `senate` to zero;
- `myopic`: set beta to zero;
- `npl_stress`: add one sample standard deviation to `npf_a`;
- report the one-period mean closure-probability level.

Replace these assumptions when the organizer supplies exact definitions.

In [8]:
provisional_cf = P1CounterfactualConfig(
    # The API refuses to compute undocumented counterfactuals unless this
    # acknowledgement is explicit.
    acknowledge_provisional=True,
    npl_shift_in_standard_deviations=1.0,
    report="level",
)

# Re-estimate all three datasets so every result object carries the same
# counterfactual assumptions and can fill the complete submission template.
all_results_with_cf = fit_practicum1_all(
    DATA,
    config=config,
    counterfactual_config=provisional_cf,
)
all_results_with_cf.summary()

/Users/bc3139/repo/summer2026/DSE2026/src/dse_practicum/practicum1.py:1002: RuntimeWarning: Practicum 1 counterfactual definitions are provisional: reporting one-period mean closure probabilities.
  result.counterfactuals = compute_provisional_counterfactuals(

/Users/bc3139/repo/summer2026/DSE2026/src/dse_practicum/practicum1.py:1002: RuntimeWarning: Practicum 1 counterfactual definitions are provisional: reporting one-period mean closure probabilities.
  result.counterfactuals = compute_provisional_counterfactuals(

/Users/bc3139/repo/summer2026/DSE2026/src/dse_practicum/practicum1.py:1002: RuntimeWarning: Practicum 1 counterfactual definitions are provisional: reporting one-period mean closure probabilities.
  result.counterfactuals = compute_provisional_counterfactuals(

   dataset                           quantity     estimate
0        A                              sigma    47.813325
1        A  beta (calibration; not submitted)     0.960000
2        A                        theta_const  -356.161916
3        A                   theta_log_assets   459.366358
4        A                 theta_log_assets^2   -20.268342
5        A                        theta_npf_a  6821.286014
6        A                          theta_roa  -829.263120
7        A                    theta_realest_a  4516.696201
8        A                        theta_house     0.038824
9        A                  theta_house*npf_a  -168.711315
10       A                    cf_no_political     0.069018
11       A                          cf_myopic     0.307755
12       A                      cf_npl_stress     0.069341
13       B                              sigma    50.536245
14       B  beta (calibration; not submitted)     0.960000
15       B                        theta_const -1507.313831
16       B                   theta_log_assets   606.826567
17       B                 theta_log_assets^2   -24.907838
18       B                        theta_npf_a  7251.114347
19       B                          theta_roa  -785.546680
20       B                    theta_realest_a  4317.627457
21       B                        theta_house  -208.702877
22       B             theta_house*log_assets    16.914116
23       B                    cf_no_political     0.055893
24       B                          cf_myopic     0.256541
25       B                      cf_npl_stress     0.056838
26       C                              sigma   183.284639
27       C  beta (calibration; not submitted)     0.700000
28       C                        theta_const  1104.045220
29       C                   theta_log_assets   180.334951
30       C                 theta_log_assets^2   -11.995034
31       C                        theta_npf_a  8089.867854
32       C                          theta_roa -2120.556524
33       C                    theta_realest_a  6022.115236
34       C                       theta_senate   -11.109898
35       C                        theta_trend    91.102371
36       C                    cf_no_political     0.029386
37       C                          cf_myopic     0.047253
38       C                      cf_npl_stress     0.031142

## 6. Create the submission file

This uses the official template as the schema and refuses missing, extra, or
non-finite rows. This is a competition-data validation step rather than a
method taken from Kang et al.

In [9]:
# Filling the template by row name prevents squared/interaction terms from
# silently moving to the wrong dataset or sign convention.
submission = all_results_with_cf.to_submission(
    DATA / "sample_submission.csv",
    ROOT / "practicum" / "practicum1_submission.csv",
)
submission

                          Id   Prediction
0                    A_sigma    47.813325
1              A_theta_const  -356.161916
2         A_theta_log_assets   459.366358
3       A_theta_log_assets^2   -20.268342
4              A_theta_npf_a  6821.286014
5                A_theta_roa  -829.263120
6          A_theta_realest_a  4516.696201
7              A_theta_house     0.038824
8        A_theta_house*npf_a  -168.711315
9          A_cf_no_political     0.069018
10               A_cf_myopic     0.307755
11           A_cf_npl_stress     0.069341
12                   B_sigma    50.536245
13             B_theta_const -1507.313831
14        B_theta_log_assets   606.826567
15      B_theta_log_assets^2   -24.907838
16             B_theta_npf_a  7251.114347
17               B_theta_roa  -785.546680
18         B_theta_realest_a  4317.627457
19             B_theta_house  -208.702877
20  B_theta_house*log_assets    16.914116
21         B_cf_no_political     0.055893
22               B_cf_myopic     0.256541
23           B_cf_npl_stress     0.056838
24                   C_sigma   183.284639
25             C_theta_const  1104.045220
26        C_theta_log_assets   180.334951
27      C_theta_log_assets^2   -11.995034
28             C_theta_npf_a  8089.867854
29               C_theta_roa -2120.556524
30         C_theta_realest_a  6022.115236
31            C_theta_senate   -11.109898
32             C_theta_trend    91.102371
33         C_cf_no_political     0.029386
34               C_cf_myopic     0.047253
35           C_cf_npl_stress     0.031142

## Paper cross-reference

| Notebook component | Kang, Lowery, and Wardlaw (2015) |
|---|---|
| Terminal closure and CCP inversion | Section 1.2, Equations (4)-(6), pp. 1067-1068 |
| Monetary/nonmonetary cost split | Section 1.2, Equation (7), p. 1068 |
| Five-stage estimator and structural residual | Section 1.2, Equations (8)-(9), pp. 1068-1069 |
| Monetary-cost pre-estimation | Section 2.2, pp. 1075-1078 |
| Transition process and future expectations | Section 2.3, pp. 1079-1081 |
| Flexible closure CCP | Section 2.4, pp. 1081-1083 |
| Instrument choice and GMM | Appendix A.1.1, p. 1097 |
| Temporary-policy counterfactuals | Section 4 and Appendix A.2, pp. 1093-1100 |

**Reference:** Kang, K., Lowery, R., and Wardlaw, M. (2015), "The Costs of
Closing Failed Banks: A Structural Estimation of Regulatory Incentives,"
*Review of Financial Studies* 28(4), 1060-1102.